---

- name: Setup Icinga 2 master certificate authority
  shell: "{{ icinga2_binary }} node setup --master --cn {{ icinga2_master_fqdn }}"
  args:
    creates: "/var/lib/icinga2/ca/ca.crt"
  notify: Test config before restart icinga 2

- name: restart icinga if CA initiated
  meta: flush_handlers

