---


- name: give fqdn
  debug:
    msg: "{{icinga2_master_fqdn}}"

- name: generate ticket on the icinga master and save it as a variable
  shell: "{{ icinga2_binary }} pki ticket --cn {{ inventory_hostname }}"
  register: icinga2_client_ticket
  changed_when: False
  delegate_to: "{{icinga2_master_fqdn}}"

- name: give ticket
  debug:
    msg: "{{ icinga2_client_ticket['stdout'] }}"
  ignore_errors: '{{ ansible_check_mode }}'

- name: ensure pki folder is created
  file:
    dest: /etc/icinga2/pki
    state: directory
    mode: 0700
    owner: "{{icinga2_user[ansible_os_family]}}"
    group: "{{icinga2_group[ansible_os_family]}}"

- name: create cert
  shell: |
    {{ icinga2_binary }} pki new-cert \
    --cn {{ inventory_hostname }} \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt
  args:
    creates: "/etc/icinga2/pki/{{ inventory_hostname }}.crt"
  notify: Test config before restart icinga 2
  ignore_errors: '{{ ansible_check_mode }}'

- name: save the masters cert as trustedcert
  shell: |
    {{ icinga2_binary }} pki save-cert \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
    --trustedcert /etc/icinga2/pki/trusted-master.crt \
    --host {{ icinga2_master_fqdn }}
  args:
    creates: /etc/icinga2/pki/trusted-master.crt
  notify: Test config before restart icinga 2
  ignore_errors: '{{ ansible_check_mode }}'

- name: request the certificate from the icinga server
  shell: |
    {{ icinga2_binary }} pki request \
    --host {{ icinga2_master_fqdn }} \
    --port {{ icinga2_api_port }} \
    --ticket {{ icinga2_client_ticket['stdout'] }} \
    --key /etc/icinga2/pki/{{ inventory_hostname }}.key \
    --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt \
    --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.crt
  args:
    creates: /etc/icinga2/pki/ca.crt
  notify: Test config before restart icinga 2
  ignore_errors: '{{ ansible_check_mode }}'

- name: node setup
  shell: |
    {{ icinga2_binary }} node setup \
    --ticket {{ icinga2_client_ticket['stdout'] }} \
    --endpoint {{ icinga2_master_fqdn }} \
    --zone {{ inventory_hostname }} \
    --master_host {{ icinga2_master_fqdn }} \
    --trustedcert /etc/icinga2/pki/trusted-master.crt \
    --cn {{ inventory_hostname }} \
    --accept-commands \
    --accept-config
  args:
    creates: /etc/icinga2/zones.conf.orig
  when: icinga2_role == "agent"
  notify: Test config before restart icinga 2
  ignore_errors: '{{ ansible_check_mode }}'
  
