---

- name: "Enable icinga2 feature {{icinga2_feature_name}} - {{ icinga2_feature_name in icinga2_features }}"
  file:
    src: "../features-available/{{icinga2_feature_name}}.conf"
    dest: "/etc/icinga2/features-enabled/{{icinga2_feature_name}}.conf"
    owner: root
    group: root
    state: "{{'link' if ( icinga2_feature_name in icinga2_features ) else 'absent' }}"
  notify: Test config before restart icinga 2
