---

- name: Manage icinga2 apiusers.conf
  template:
    src: apiusers.conf.j2
    dest: /etc/icinga2/objects/apiusers.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0640
  notify: Test config before restart icinga 2
