---

- name: install the latest version of icinga2-ido-mysql
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2-ido-mysql

- name: Install MySQL-python on RedHat
  yum:
    name: MySQL-python
    state: present
  when: ansible_os_family == 'RedHat'

- name: Check IDO schema version in MySQL (no ssl)
  command:
    mysql
    -h {{ icinga2_ido_host|quote }}
    -u {{ icinga2_ido_user|quote }}
    -p{{ icinga2_ido_password|quote }}
    {{ icinga2_ido_dbname|quote }}
    -Ns -e "SHOW TABLES LIKE 'icinga_dbversion'"
  changed_when: False
  register: table_exists
  when: icinga2_ido_options.ssl_key is not defined

- name: Check IDO schema version in MySQL (ssl)
  command:
    mysql
    -h {{ icinga2_ido_host|quote }}
    -u {{ icinga2_ido_user|quote }}
    -p{{ icinga2_ido_password|quote }}
    {{ icinga2_ido_dbname|quote }}
    --ssl=TRUE
    --ssl-cert={{ icinga2_ido_options.ssl_cert }}
    --ssl-key={{ icinga2_ido_options.ssl_key }}
    -Ns -e "SHOW TABLES LIKE 'icinga_dbversion'"
  changed_when: False
  register: table_exists
  when: icinga2_ido_options.ssl_key is defined

- name: Import icinga2 schema (no ssl)
  mysql_db:
    state: import
    name: "{{ icinga2_ido_dbname }}"
    login_host: "{{ icinga2_ido_host }}"
    login_user: "{{ icinga2_ido_user }}"
    login_password: "{{ icinga2_ido_password|default(omit) }}"
    ssl_cert: "{{ icinga2_ido_options.ssl_key|default(omit) }}"
    ssl_key: "{{ icinga2_ido_options.ssl_cert|default(omit) }}"
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  ignore_errors: yes
  when: table_exists.stdout == ""

- name: configure feature ido-mysql
  template:
    dest: "/etc/icinga2/features-available/ido-mysql.conf"
    src: templates/ido-mysql.j2
    mode: 0640

