---
- name: Add icinga2 repository
  yum_repository:
    name: icinga-stable-release
    description: icinga2 latest repository
    baseurl: "{{ icinga2_yum_repo.baseurl }}"
    gpgkey: "{{ icinga2_yum_repo.gpgkey }}"
  when: icinga2_manage_repo_icinga

- name: Add epel
  yum:
    name: epel-release
    state: present
  when: icinga2_manage_repo_epel

- name: Install icinga2 basic packages
  yum:
    name: "{{ item }}"
    state: "{{ icinga2_state }}"
  register: track_icinga2_install
  with_items: "{{ packages_redhat }}" 
